name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library-check:
    name: Build Library
    runs-on: macos-latest
    strategy:
      matrix:
        destination:
          - platform=iOS Simulator,name=iPhone 15 Pro
          - platform=macOS
        config:
          - debug
          - release
    steps:
      - name: Install Dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          brew install mise
          mise install
          mise use --global xcbeautify

      - uses: actions/checkout@v4

      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Build Package on ${{ matrix.destination }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mise use --global xcbeautify
          set -o pipefail && xcodebuild \
            -workspace ./FluentIcon.xcworkspace \
            -scheme FluentIcon \
            -destination '${{ matrix.destination }}' \
            -configuration ${{ matrix.config }} \
            build | xcbeautify --renderer github-actions

      - name: Build Package ${{ matrix.config }}
        run: swift build -c ${{ matrix.config }}
