name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library-check:
    name: Library (Swift 5.10)
    runs-on: macos-14
    strategy:
      matrix:
        config:
          - debug
          - release
        sdk:
          - macosx
          - iphonesimulator
    steps:
      - name: Install Dependencies
        run: |
          brew install xcbeautify

      - uses: actions/checkout@v4

      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Build Package ${{ matrix.config }}
        run: swift build -c ${{ matrix.config }}

      - name: Build Example Project ${{ matrix.config }}
        run: |
          set -o pipefail \
          && xcodebuild \
            -workspace FluentIcon.xcworkspace \
            -scheme Example \
            -destination "platform=${{ matrix.sdk }}" \
            -configuration ${{ matrix.config }} \
            build \
          | xcbeautify --renderer github-actions
