name: Format

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  swift_format:
    name: swift-format
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Install All Tools
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          brew install mise
          mise install

      - name: Format
        run: swiftformat .

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: format code"
          branch: "master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
