name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unittest:
    name: Unit Test
    runs-on: macos-14
    strategy:
      matrix:
        destination:
          - platform=iOS Simulator,name=iPhone 15 Pro
          - platform=macOS
    steps:
      - name: Install Dependencies
        run: |
          brew install mise
          mise install
          mise use --global xcbeautify

      - uses: actions/checkout@v4

      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Test Package ${{ matrix.destination }}
        run: |
          mise use --global xcbeautify
          xcodebuild \
            -workspace ./FluentIcon.xcworkspace \
            -scheme FluentIcon \
            -destination ${{ matrix.destination }} \
            test | xcbeautify --renderer github-actions
